# Generated by Django 2.0.1 on 2018-01-21 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybearsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('my_groups', models.ManyToManyField(to='studybearsapp.StudyGroups')),
                ('potential_locations', models.ManyToManyField(to='studybearsapp.Location')),
                ('time_availabilities', models.ManyToManyField(to='studybearsapp.Date_And_Time')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='potential_locations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_availabilities',
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybearsapp.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
